import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { ChakraProvider } from "@chakra-ui/react";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Firebase Authentication App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <ChakraProvider>
        <main className={styles.main}>
          <h1 className={styles.title}>home画面だよ</h1>
        </main>
      </ChakraProvider>
    </div>
  );
};

export default Home;
